### PR TITLE
fix(ci/cd): Update and fix actions to get rid of warnings

### PR DESCRIPTION
**Pull request by jiriks74**
There's an insane amount of warning s in Actions:

image

### CODE REVIEW

**Comment by jiriks74** [comment]
I will work on this more later. I created a draft to indicate my work on it and you're able to commit to this as well, if you wish to.

**Comment by DxsSucuk** [comment]
Has already been fixed.

**Comment by jiriks74** [comment]
Shit. Sorry about that. Had some stuff I had to take care of and this got lost in the list of issues I'm trying to get solved. Glad you were able to fix it!

**Comment by DxsSucuk** [comment]
All good mate, they got fixed from just updating the action versions used.

**Pull request closed without merging**
